# Generated by Django 3.1 on 2022-02-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDiagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('1', '10:00-11:00'), ('2', '11:00-12:00'), ('3', '12:00-13:00'), ('4', '13:00-14:00'), ('5', '14:00-15:00'), ('6', '15:00-16:00'), ('7', '16:00-17:00'), ('8', '17:00-18:00'), ('9', '18:00-19:00'), ('10', '19:00-20:00')], max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_diagnostic_client', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_diagnostic_master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
